---
title: "ps2"
author: "Jacob Stenstrom"
date: '2024-02-12'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

## Empirical Question

```{r ps1}
library(tidyverse)
library(sandwich)
library(lmtest)
library(jtools)
library(sjPlot)
library(sjmisc)
library(sjlabelled)
library(estimatr)
library(haven)
library(ivreg)
library(oaxaca)

x<-rnorm(1000,mean = 0,sd=10)
df_ps2 <- data.frame()
stp='stp'
df_ps2 <- df_ps2 %>% add_column(stp)
df_ps2$stp <- as.double(df_ps2$stp)
i<-1

#df_ps2<-df_ps2 %>% add_row(stp=x[i]+df_ps2[1,1])
while (i < length(x)+1){
  
  if(i==1){
    df_ps2<-df_ps2 %>% add_row(stp=x[i])
  }else{
    t<-df_ps2[i-1,1]
    df_ps2<-df_ps2 %>% add_row(stp=x[i]+t)#+df_ps2[i-1,1])
  }
  
  i=i+1
}
df_ps2$t <- seq.int(nrow(df_ps2))
```

```{r newey-west}
fit<-lm(stp~t,data = df_ps2)
nw_m<-NeweyWest(fit)
nw_m
```

```{r qlr}
library(zoo)
library(dynlm)
library(desk)

test<-qlr.test(fit,from = 150,to=850)
test
```